### ISSUE TITLE
mkdirSync fails silently

### ISSUE THREAD

**Issue by lucaorio** [skpm/fs#15]
It seems like `fs.existsSync` doesn't create any folder. No error is returned, either.

```js
import * as fs from '@skpm/fs';

// ...

fs.mkdirSync('~/test/abc', { recursive: true }, err => {
  if (err) throw err;
});

```

**Comment by mathieudutour** [comment]
1. `fs.mkdirSync` doesn't take a callback as an argument since it's synchronous.
2. '~/test/abc' is equivalent to `./~/test/abc` which is probably not what you want. If you want to resolve `~`, you can use something like https://github.com/sindresorhus/untildify/
3. I just don't think it's failing, just that it creates a folder where you don't expect it

**Comment by lucaorio** [comment]
@mathieudutour Thanks for helping. The snippet below works well, indeed!
```js
const path = '/Users/myself/test/abc';
!fs.existsSync(path) && fs.mkdirSync(path);
```

Unfortunately, Untildify returns an empty string :(
Do you have any other advice on how I can resolve that path?

**Comment by mathieudutour** [comment]
```js
const os = require('os');

const home = os.homedir();

const untiltify = input => {
	if (typeof input !== 'string') {
		throw new TypeError(`Expected a string, got ${typeof input}`);
	}

	return home ? input.replace(/^~(?=$|\/|\\)/, home) : input;
};

console.log(untiltify('~/test'))
```

works fine for me (which is the code of https://github.com/sindresorhus/untildify/). What version of Sketch are you using?

**Comment by lucaorio** [comment]
I'm using 53.1!

By the way, _untiltify_ wasn't working when I was trying to run everything from within a plugin. I'm now slowly moving pretty much everything I can outside of it, and I can confirm you that _untiltify_ works well :)
